services:
  - type: web
    name: detecta-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m app.main"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
